
PAPERS=1A-2.pdf 1A-3.pdf 1A-4.pdf 4A-10.pdf 4A-11.pdf 4A-9.pdf 4B-12.pdf 4B-13.pdf 5B-18.pdf 5B-19.pdf 5B-20.pdf 6A-21.pdf 6A-22.pdf
ORGANIZED=3A-K6.pdf
POSTERS=P01.pdf P02.pdf P03.pdf P04.pdf P05.pdf P06.pdf P07.pdf P08.pdf P09.pdf P10.pdf P11.pdf P12.pdf P13.pdf P14.pdf P15.pdf P16.pdf

HTMLS=index.html images/fukuoka.jpg css/2016.css css/base-2016.css css/c-2016.css css/hideme.css css/navbar.css

ARCHIVE=ACSI2016.zip

${ARCHIVE}: ${PAPERS} ${ORGANIZED} ${POSTERS} ${HTMLS}
	rm -rf ${ARCHIVE}
	zip ${ARCHIVE}  ${PAPERS} ${ORGANIZED} ${POSTERS} ${HTMLS}
